import { useState } from "react";
import { ArrowRight, ChevronDown, ChevronUp } from "lucide-react";
import { Link } from "wouter";
import PublicLayout from "@/components/PublicLayout";
import { Button } from "@/components/ui/button";

function Clause({ number, title, children }: { number: string; title: string; children: React.ReactNode }) {
  const [open, setOpen] = useState(false);
  return <div className="border-b border-gray-200 last:border-0"><button type="button" onClick={() => setOpen(!open)} className="group flex w-full items-center justify-between px-6 py-5 text-left transition-colors hover:bg-gray-50"><span className="font-heading text-base font-bold text-navy"><span className="mr-2 text-teal">{number}.</span>{title}</span><span className={`ml-4 flex h-8 w-8 shrink-0 items-center justify-center rounded-full border-2 transition-all ${open ? "border-teal bg-teal text-white" : "border-gray-300 text-gray-400 group-hover:border-teal group-hover:text-teal"}`}>{open ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}</span></button>{open && <div className="space-y-3 border-t border-gray-100 bg-gray-50/50 px-6 pb-6 pt-4 text-sm leading-relaxed text-gray-700">{children}</div>}</div>;
}
function P({ children }: { children: React.ReactNode }) { return <p className="leading-relaxed">{children}</p>; }
function Sub({ title, children }: { title: string; children: React.ReactNode }) { return <div className="mt-3"><p className="mb-1.5 font-semibold text-navy">{title}</p><div className="space-y-2">{children}</div></div>; }
function UL({ items }: { items: React.ReactNode[] }) { return <ul className="list-disc space-y-1.5 pl-5">{items.map((item, index) => <li key={index}>{item}</li>)}</ul>; }

export default function Terms() {
  return <PublicLayout>
    <section className="bg-navy py-16 text-white lg:py-24"><div className="container max-w-3xl text-center"><div className="mb-4 text-sm font-semibold uppercase tracking-widest text-teal-300">Legal</div><h1 className="mb-6 font-heading text-4xl font-extrabold lg:text-5xl">Terms of Service</h1><p className="text-lg leading-relaxed text-gray-300">Memorandum of Understanding — Referral Partnership Model</p><p className="mt-3 text-sm text-gray-400">Silara Marketing (ACN 688 042 177) | apgpaccommodation.com.au</p></div></section>
    <section className="border-b border-teal/20 bg-teal-light py-10"><div className="container max-w-4xl"><p className="text-center text-sm leading-relaxed text-gray-700">These Terms of Service form the detailed APGP Memorandum of Understanding between Silara Marketing and participating accommodation providers. The signed Silara Marketing Referral Agreement governs agreement-specific commercial terms and prevails if there is an inconsistency.</p></div></section>
    <section className="bg-white py-12"><div className="container max-w-4xl"><div className="overflow-hidden rounded-3xl border border-gray-100 bg-white shadow-sm">
      <Clause number="1" title="Parties and Purpose"><Sub title="1.1 Silara Marketing and APGP"><P>These Terms of Service (MOU) are entered into by Silara Marketing (ACN 688 042 177) ("Silara Marketing"), which operates the Accommodation Provider Growth Program ("APGP"). APGP is an independent business-to-business referral and placement facilitation platform. It does not provide accommodation, care services, support coordination, or NDIS supports directly to Participants.</P></Sub><Sub title="1.2 Accommodation Provider"><P>The other party is the accommodation provider identified in the signed Silara Marketing Referral Agreement ("Provider"). The Provider owns, manages, leases, or otherwise operates disability accommodation and participates in APGP subject to these Terms and the signed Referral Agreement.</P></Sub><Sub title="1.3 Purpose"><P>APGP facilitates introductions between Providers and Participants seeking disability accommodation. These Terms set out the detailed operational, privacy, compliance and commercial framework. Nothing creates a partnership, joint venture, agency, employment or fiduciary relationship.</P></Sub></Clause>
      <Clause number="2" title="Definitions and Document Priority"><Sub title="2.1 Definitions"><UL items={[<><strong>Introduction:</strong> Silara Marketing providing the Provider with a Participant Evaluation Form or a Participant&apos;s identifying details.</>, <><strong>Participant:</strong> a person with disability introduced through APGP.</>, <><strong>Participant Information:</strong> information concerning a Participant, including contact, funding, disability, health and support-needs information.</>, <><strong>Successful Referral:</strong> has the meaning in the signed Referral Agreement.</>, <><strong>Related Entity:</strong> has the meaning in the signed Referral Agreement.</>, <><strong>Referral Fee:</strong> the provider-only fee payable on a Successful Referral under the signed Referral Agreement.</>]}/></Sub><Sub title="2.2 Priority"><P>The signed Silara Marketing Referral Agreement incorporates these Terms. If there is any inconsistency, the signed Referral Agreement prevails, including for the Referral Fee, the definition and timing of a Successful Referral, invoicing and payment obligations, referral entitlement, and non-circumvention.</P></Sub></Clause>
      <Clause number="3" title="Nature of the Relationship"><Sub title="3.1 Independent Parties"><P>The parties act as independent contracting parties. Neither may bind the other, make commitments for the other, or represent that it has authority to do so without written authority.</P></Sub><Sub title="3.2 Independent Compliance"><P>Each party remains solely responsible for its own legal, regulatory, operational, accommodation and service-delivery obligations.</P></Sub></Clause>
      <Clause number="4" title="Program Overview"><Sub title="4.1 Non-Exclusive Participation"><P>Participation is non-exclusive. The Provider remains free to engage with other referral sources, and Silara Marketing is not required to provide referrals exclusively to the Provider.</P></Sub><Sub title="4.2 No Guarantee"><P>Silara Marketing does not guarantee the number, frequency, suitability or outcome of any Introduction, occupancy level, vacancy reduction or commercial result. The Provider retains discretion to accept or decline any Participant.</P></Sub><Sub title="4.3 Participant Choice"><P>Every Participant retains full choice and control concerning accommodation, support providers and services. APGP must not pressure or improperly influence a Participant&apos;s decision.</P></Sub></Clause>
      <Clause number="5" title="Participant Safeguards and NDIS Compliance"><Sub title="5.1 Provider-Only Commercial Arrangement"><P>APGP is a business-to-business commercial arrangement between Silara Marketing and the Provider. No Referral Fee or other commercial amount may be charged to, recovered from, invoiced to, deducted from, or claimed against a Participant, their family, nominee, support coordinator, plan manager or NDIS plan.</P></Sub><Sub title="5.2 Transparency"><P>Silara Marketing will obtain the Participant&apos;s consent before disclosing Participant Information and may disclose the commercial referral arrangement in accurate, non-misleading terms. Neither party may state or imply that a Referral Fee limits Participant choice.</P></Sub><Sub title="5.3 Ethical Conduct"><P>No payment, benefit or incentive under APGP is intended to improperly influence Participant decision-making or constitute a prohibited inducement, kickback or benefit.</P></Sub></Clause>
      <Clause number="6" title="Referral Services and Provider Responsibilities"><Sub title="6.1 APGP Services"><P>Silara Marketing may identify and introduce Participants, facilitate initial introductions, and support communication and coordination in the placement process. APGP does not guarantee an outcome and does not assume the Provider&apos;s accommodation or service obligations.</P></Sub><Sub title="6.2 Provider Responsibilities"><UL items={["Independently assess the suitability of every Participant and make all acceptance decisions.", "Ensure accommodation and any services meet all applicable legal and regulatory requirements.", "Communicate accurately and respectfully with Participants and maintain any required registrations, insurances and standards.", "Promptly communicate placement progression or a decision not to proceed as required by the signed Referral Agreement."]}/></Sub></Clause>
      <Clause number="7" title="Referral Fee, Successful Referral and Payment"><Sub title="7.1 Agreement-Specific Commercial Terms"><P>The signed Referral Agreement is the sole source of the Referral Fee amount and other agreement-specific commercial terms. These Terms do not publish or vary that amount.</P></Sub><Sub title="7.2 Trigger and Payment"><P>A Referral Fee is payable only after a Successful Referral as defined in the signed Referral Agreement. Its trigger, invoice date, payment period, late-payment consequence and provider notification obligation are governed by that Agreement. No upfront, joining, subscription, periodic, advertising or assessment fee is payable unless separately recorded in a written agreement signed by both parties.</P></Sub><Sub title="7.3 No Recovery from Participants"><P>The Provider must not attempt to recover any Referral Fee, late payment charge or other APGP commercial cost from a Participant or their NDIS funding.</P></Sub></Clause>
      <Clause number="8" title="Referral Entitlement and Non-Circumvention"><Sub title="8.1 Registered Introductions"><P>An Introduction remains subject to the referral entitlement and non-circumvention provisions of the signed Referral Agreement. The Provider must not use a Related Entity, third party, delayed placement, alternative property or re-characterised arrangement to avoid or reduce the Referral Fee.</P></Sub><Sub title="8.2 Participant Freedom"><P>These obligations apply to the Provider only. They do not bind a Participant or limit a Participant&apos;s freedom to choose any provider, property or support arrangement.</P></Sub></Clause>
      <Clause number="9" title="Participant Information, Privacy and Confidentiality"><Sub title="9.1 Permitted Use"><P>Participant Information may be used only to assess, respond to and, if the referral proceeds, accommodate and support the relevant Participant. It must not be used to market or promote services, add a Participant to a marketing list, or be sold, shared, traded or disclosed to another provider, broker, agent, landlord or organisation except with express consent or as required by law.</P></Sub><Sub title="9.2 Protection and Destruction"><P>Each party must protect Participant Information in accordance with the Privacy Act 1988 (Cth). If a referral does not proceed, the Provider must securely destroy or permanently de-identify Participant Information, including records and printed material, within seven (7) days where reasonably practicable. On request, the Provider must confirm compliance in writing.</P></Sub><Sub title="9.3 Data Incidents and Commercial Confidentiality"><P>The Provider must notify Silara Marketing within twenty-four (24) hours of becoming aware of unauthorised access, loss or disclosure and comply with applicable notifiable data breach obligations. Each party must keep commercial terms confidential except where lawfully required or disclosed to professional advisers, insurers or auditors.</P></Sub></Clause>
      <Clause number="10" title="Marketing and Communications"><Sub title="10.1 Branding"><P>Neither party may use the other&apos;s name, logo or branding publicly without prior written consent. Neither may represent that APGP participation is an endorsement, accreditation or guarantee.</P></Sub><Sub title="10.2 Consumer Law"><P>All marketing and communications must comply with Australian Consumer Law. Neither party may make false, misleading or unsubstantiated claims about referrals, placement outcomes, compliance status or APGP&apos;s role.</P></Sub></Clause>
      <Clause number="11" title="Term and Termination"><Sub title="11.1 Term"><P>The signed Referral Agreement commences on execution and continues until either party terminates it on thirty (30) days&apos; written notice, unless terminated earlier under applicable law or an express written agreement.</P></Sub><Sub title="11.2 Effect"><P>Termination does not affect an amount already incurred or a Referral Fee that becomes payable in relation to a Participant introduced before termination. The referral entitlement, non-circumvention, privacy, confidentiality, compliance and any provision intended to survive continue as required by the signed Referral Agreement and these Terms.</P></Sub></Clause>
      <Clause number="12" title="Liability and Indemnities"><Sub title="12.1 Allocation of Responsibility"><P>To the maximum extent permitted by law, Silara Marketing is not responsible for a Participant&apos;s decision, a Provider&apos;s decision, the suitability of an accommodation arrangement, vacancy duration, income loss or commercial outcomes. Nothing limits liability that cannot lawfully be excluded.</P></Sub><Sub title="12.2 Provider Responsibility"><P>The Provider remains responsible for its accommodation, property-management, tenancy, care and service-delivery arrangements, and for claims arising from them or from its breach of law or these Terms.</P></Sub></Clause>
      <Clause number="13" title="Insurance"><P>The Provider must maintain appropriate insurance required by law and reasonably appropriate to its operations, including public liability and, where applicable, professional indemnity insurance. On reasonable request, the Provider must provide evidence of current cover.</P></Clause>
      <Clause number="14" title="Dispute Resolution and Governing Law"><Sub title="14.1 Good Faith Resolution"><P>If a dispute arises, the parties must first use reasonable efforts to resolve it through good-faith discussions between authorised representatives. If unresolved, either party may seek mediation before commencing formal proceedings, except where urgent relief is reasonably required.</P></Sub><Sub title="14.2 Governing Law"><P>These Terms and the signed Referral Agreement are governed by the laws of New South Wales. The parties submit to the non-exclusive jurisdiction of the courts of that State.</P></Sub></Clause>
      <Clause number="15" title="Regulatory Compliance"><P>Each party must comply with applicable laws, including the National Disability Insurance Scheme Act 2013 (Cth), NDIS Code of Conduct, Privacy Act 1988 (Cth), Spam Act 2003 (Cth) and Australian Consumer Law. Each party must act honestly, transparently and professionally and cooperate with reasonable compliance-related requests.</P></Clause>
      <Clause number="16" title="General Provisions"><Sub title="16.1 Amendments and Entire Agreement"><P>Any amendment must be in writing and signed by authorised representatives. Together with the signed Referral Agreement, these Terms record the parties&apos; agreement about the APGP referral relationship and supersede prior statements about that subject.</P></Sub><Sub title="16.2 Severability, Assignment and Notices"><P>If a provision is unenforceable, it is severed to the required extent without affecting the rest. The Provider must not assign its rights or obligations without written consent. Notices must be in writing and may be sent by email or other agreed electronic means. Electronic execution is valid and binding.</P></Sub></Clause>
    </div><p className="mt-6 text-center text-xs text-gray-400">© 2026 Silara Marketing (ACN 688 042 177). All rights reserved.</p></div></section>
    <section className="bg-navy py-16 text-center text-white"><div className="container max-w-xl"><h2 className="mb-4 font-heading text-3xl font-bold">Ready to Partner with APGP?</h2><p className="mb-8 text-gray-300">Register your organisation for free and our team will be in touch to discuss your partnership.</p><Link href="/provider/register"><Button size="lg" className="bg-teal px-10 font-semibold text-white hover:bg-teal-600">Register Now — Free <ArrowRight className="ml-2 h-4 w-4" /></Button></Link></div></section>
  </PublicLayout>;
}
